---
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8010/eureka/,http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: subjects
subject:
  words: I,You,He,She,It,They,We

---
spring:
  profiles: verbs
verb:
  words: ran,knew,had,saw,bought

---
spring:
  profiles: articles
article:
  words: a,the

---
spring:
  profiles: adjectives
adjective:
  words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: nouns
noun:
  words: boat,book,vote,seat,backpack,partition,groundhog

