---
eureka:  
  client:
    serviceUrl: 
      defaultZone: http://localhost:8010/eureka/,http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: subject
subject:
  words: I,You,He,She,It,They,We,None

---
spring:
  profiles: verb
verb:
  words: ran,knew,had,saw,bought

---
spring:
  profiles: article
article:
  words: a,the

---
spring:
  profiles: adjective
adjective:
  words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
noun:
  words: boat,book,vote,seat,backpack,partition,groundhog

