---

# Allow thymeleaf template changes to reload:
spring:
  thymeleaf:
    cache: false
    
# Zuul-proxied services can be found by calling /api/subject-service, /api/verb-service etc.
zuul:
  prefix: /api
      